import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/ui/app-slidebar";
import Navbar from "@/components/ui/navbar";
import { Button } from "@/components/ui/button";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body className="bg-black text-white">
        <SidebarProvider>
          <AppSidebar />
            <main className="flex flex-col w-full h-screen">
              <div><Navbar/></div>
              <div>{children}</div>
            </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
